apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  storageClassName: interscity-sc
  hostPath:
    path: "/mnt/data/redis"
