apiVersion: v1
kind: Service
metadata:
  name: orquestrator-service
  labels:
    app: orquestrator
  namespace: interscity
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  selector:
    app: orquestrator
