apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagger
  namespace: interscity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tagger
  template:
    metadata:
      labels:
        app: tagger
    spec:
      containers:
      - name: tagger
        image: dvitorsantos/tagger:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tagger-config
