apiVersion: v1
kind: Service
metadata:
  labels:
    app: iotcataloguer
  name: iotcataloguer-service
  namespace: interscity
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  selector:
    app: iotcataloguer
