
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resource-cataloguer
  name: resource-cataloguer-service
  namespace: interscity
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: resource-cataloguer