apiVersion: v1
kind: Service
metadata:
  name: secure-resource-adaptor-service
  labels:
    app: secure-resource-adaptor
  namespace: interscity
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  selector:
    app: secure-resource-adaptor
