
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resource-adaptor
  name: resource-adaptor-service
  namespace: interscity
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: resource-adaptor