
apiVersion: v1
kind: Service
metadata:
  labels:
    app: actuator-controller
  name: actuator-controller-service
  namespace: interscity
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: actuator-controller