apiVersion: v1
kind: Service
metadata:
  name: entity-manager-service
  labels:
    app: entity-manager
  namespace: interscity
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
  selector:
    app: entity-manager
