apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: interscity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:0.11.0
#        command:
#        - bash 
#        - -c 
#        - kong migrations up -v && /usr/local/openresty/nginx/sbin/nginx -c /usr/local/kong/nginx.conf -p /usr/local/kong/
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: KONG_PG_USER
          value: postgres
        - name: KONG_PG_PASSWORD
          value: admin
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: postgres-service