apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong-service
  namespace: interscity
spec:
  type: NodePort
  ports:
  - name: web
    port: 8000
    nodePort: 30007
  - name: api
    port: 8001
  selector:
    app: kong
  