apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-script
  namespace: interscity
data:
  psql-script.sh: |-
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE kong;
        GRANT ALL PRIVILEGES ON DATABASE kong TO postgres;
        CREATE DATABASE tagger;
        GRANT ALL PRIVILEGES ON DATABASE tagger TO postgres;
        CREATE DATABASE cdpo;
        GRANT ALL PRIVILEGES ON DATABASE cdpo TO postgres;
    EOSQL
    
    
