apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-cache
  name: mongo-cache-service
  namespace: interscity
spec:
  ports:
  - name: db
    port: 27017
  selector:
    app: mongo-cache

