
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-collector
  name: data-collector-service
  namespace: interscity
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: data-collector