apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: interscity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: registry.lsdi.ufma.br/interscity/data-collector:fix-1
        imagePullPolicy: IfNotPresent
        command: 
        - /bin/sh
        - -c
        - bundle install && bundle exec rake db:mongoid:remove_indexes db:mongoid:create_indexes && bundle exec puma -C config/puma.rb
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: interscity-config
        env:
        - name: SELF_HOST
          value: data-collector-service:3000
        - name: RAILS_RELATIVE_URL_ROOT
          value: collector
      imagePullSecrets:
        - name: interscity-secret